Add Claude tool use
imaurer/awesome-llm-json pull request #19
Opened 2024-03-19 19:10 UTC by brianjking

2024-03-19 19:59 UTC, brianjking commented
@imaurer for your review :)

2024-03-19 20:44 UTC, imaurer commented
It looks like the table formatting got changed a bit. Not sure if your markdown editor didn't like the line breaks.

2024-03-25 20:42 UTC, imaurer requested changes

2024-03-25 20:42 UTC, imaurer commented on README.md
> -| Provider     | Models                                                                             | Links
The table has bee reformatted unnecessarily. Please correct and resubmit.

2024-04-03 18:01 UTC, closed without merging